name: Docker Image CI to Docker Hub

on:
  push:
    tags:
    - v*

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      TAG_NUMBER: $GITHUB_RUN_NUMBER
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: ${{ inputs.buildx-version || env.BUILDX_VERSION }}
        driver-opts: |
          network=host
          image=${{ inputs.buildkit-image || env.BUILDKIT_IMAGE }}
    - name: Build and push
      uses: docker/build-push-action@v4.0.0
      with:
        context: ./
        file: ./dockerfile
        platforms: linux/amd64,linux/arm64
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.buildx.outputs.name }}:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.buildx.outputs.name }}:${{steps.tag.outputs.tag}}
